### ISSUE TITLE
Performance Issue: reward_module.to(torch.bfloat16) Takes a Long Time After apply_monkey_patch in RewardModelWorker (verl/workers/fsdp_workers.py)

### ISSUE THREAD

**Issue by xingyunjohn1** [volcengine/verl#2078]
In the `RewardModelWorker` class (`_build_worker` method) in `verl/workers/fsdp_workers.py`, I noticed the following code:
```python
with init_context(), warnings.catch_warnings():
    warnings.simplefilter("ignore")
    model_config.classifier_dropout = 0.0
    reward_module = AutoModelForTokenClassification.from_pretrained(
        pretrained_model_name_or_path=local_path,
        config=model_config,
        torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
        trust_remote_code=trust_remote_code,
    )

    apply_monkey_patch(
        model=reward_module,
        use_remove_padding=config.model.get("use_remove_padding", False),
        ulysses_sp_size=self.ulysses_sequence_parallel_size,
    )

    reward_module.to(torch.bfloat16)
```
The model is initially loaded with `torch.bfloat16` precision. However, after calling `apply_monkey_patch`, the model parameters' precision changes. As a result, running r`eward_module.to(torch.bfloat16)` on a large model (e.g., 32B) takes a very long time—up to half an hour or longer. Based on GPU utilization monitoring, it appears that this operation is only performed on a single GPU, even if multiple GPUs are available. This precision conversion process consumes a large amount of CPU memory, with a total usage of approximately 240 GB.

Question:
Is there any way to speed up this operation?

Why does `reward_module.to(torch.bfloat16)` take so long after `apply_monkey_patch`?
Is it possible to leverage multiple GPUs for this process or otherwise accelerate it?
Thank you!

Below my configuration:
```yaml
# the ppo trainer split config will override default ppo_trainer.yaml

hydra:
  searchpath:
    - file:///checkpoint/binary/train_package/verl/verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  tokenizer: null
  train_files:
    - /data/ppo_data_160/train.parquet # 160 samples
  val_files:
    - /data/ppo_data_160/test.parquet # 160 samples
  prompt_key: prompt
  max_prompt_length: 4096
  max_response_length: 512
  train_batch_size: 48
  val_batch_size: null # DEPRECATED: Validation datasets are sent to inference engines as a whole batch, which will schedule the memory themselves
  return_raw_input_ids: False  # This should be set to true when the tokenizer between policy and rm differs
  return_raw_chat: True
  return_full_prompt: False
  shuffle: True

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: /data/models/Qwen/Qwen3-32B
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: True
    use_remove_padding: True
  actor:
    strategy: fsdp  # This is for backward-compatibility
    ppo_mini_batch_size: ${data.train_batch_size}
    ppo_micro_batch_size: null # will be deprecated, use ppo_micro_batch_size_per_gpu
    ppo_micro_batch_size_per_gpu: 1
    use_dynamic_bsz: False
    ppo_max_token_len_per_gpu: 16384 # n * ${data.max_prompt_length} + ${data.max_response_length}
    grad_clip: 1.0
    clip_ratio: 0.2
    entropy_coeff: 0.0
    use_kl_loss: False # True for GRPO
    kl_loss_coef: 0.001 # for grpo
    kl_loss_type: low_var_kl # for grpo
    ppo_epochs: 10
    shuffle: False
    ulysses_sequence_parallel_size: 1 # sp size
    optim:
      lr: 1e-6
      lr_warmup_steps: -1 # Prioritized. Negative values mean delegating to lr_warmup_steps_ratio.
      lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
      min_lr_ratio: null   # only useful for warmup with cosine
      warmup_style: constant  # select from constant/cosine
      total_training_steps: -1  # must be override by program
    fsdp_config:
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      param_offload: False
      optimizer_offload: False
      fsdp_size: -1
      # model_dtype: bfloat16
    checkpoint:
      contents: ['model', 'hf_model', 'optimizer', 'extra']  # with 'hf_model' you can save whole model as hf format, now only use sharded model checkpoint to save space
  ref:
    strategy: fsdp
    fsdp_config:
      param_offload: False
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
    log_prob_micro_batch_size: null # will be deprecated, use log_prob_micro_batch_size_per_gpu
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
  rollout:
    name: vllm
    temperature: 1.0
    top_k: -1 # 0 for hf rollout, -1 for vllm rollout
    top_p: 1
    prompt_length: ${data.max_prompt_length}  # not use for opensource
    response_length: ${data.max_response_length}
    # for vllm rollout
    dtype: bfloat16 # should align with FSDP
    gpu_memory_utilization: 0.8
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 8
    max_num_batched_tokens: 4096
    max_num_seqs: 8
    log_prob_micro_batch_size: null # will be deprecated, use log_prob_micro_batch_size_per_gpu
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    disable_log_stats: True
    enable_chunked_prefill: False # could get higher throughput
    # for hf rollout
    do_sample: True
    # number of responses (i.e. num sample times)
    n: 1 # > 1 for grpo
    val_kwargs:
      # sampling parameters for validation
      top_k: -1 # 0 for hf rollout, -1 for vllm rollout
      top_p: 1.0
      temperature: 0
      n: 1
      do_sample: False # default eager for validation

critic:
  strategy: fsdp
  optim:
    lr: 1e-5
    lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
    min_lr_ratio: null   # only useful for warmup with cosine
    warmup_style: constant  # select from constant/cosine
    total_training_steps: -1  # must be override by program
  model:
    path: /data/models/Qwen/Qwen3-32B
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: True
    use_remove_padding: False
    fsdp_config:
      param_offload: False
      optimizer_offload: False
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      fsdp_size: -1
  ppo_mini_batch_size: ${actor_rollout_ref.actor.ppo_mini_batch_size}
  ppo_micro_batch_size: null # will be deprecated, use ppo_micro_batch_size_per_gpu
  ppo_micro_batch_size_per_gpu: 1
  forward_micro_batch_size: ${critic.ppo_micro_batch_size}
  forward_micro_batch_size_per_gpu: ${critic.ppo_micro_batch_size_per_gpu}
  use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
  ppo_max_token_len_per_gpu: 32768 # (${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}) * 2
  forward_max_token_len_per_gpu: ${critic.ppo_max_token_len_per_gpu}
  ulysses_sequence_parallel_size: 1 # sp size
  ppo_epochs: ${actor_rollout_ref.actor.ppo_epochs}
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5

reward_model:
  enable: True
  strategy: fsdp
  model:
    input_tokenizer: ${actor_rollout_ref.model.path}  # set this to null if the chat template is identical
    path: /data/rm/checkpoint/checkpoint-50
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: False
    fsdp_config:
      min_num_params: 0
      param_offload: False
      fsdp_size: -1
  micro_batch_size: null # will be deprecated, use micro_batch_size_per_gpu
  micro_batch_size_per_gpu: 1 # set a number
  max_length: null
  ulysses_sequence_parallel_size: 1 # sp size
  use_dynamic_bsz: ${critic.use_dynamic_bsz}
  forward_max_token_len_per_gpu: ${critic.forward_max_token_len_per_gpu}
  reward_manager: naive

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: gae
  use_kl_in_reward: False
  kl_penalty: kl  # how to estimate kl divergence
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

trainer:
  total_epochs: 30
  total_training_steps: null
  logger: [ 'console', 'tensorboard']
  log_val_generations: 0
  nnodes: 2
  n_gpus_per_node: 8
  save_freq: 1
  # auto: find the last ckpt to resume. If can't find, start from scratch
  resume_mode: auto # or disable or resume_path if resume_from_path is set
  resume_from_path: null
  test_freq: 1
  critic_warmup: 0
  default_hdfs_dir: null
  val_before_train: True

ray_init:
  num_cpus: null # `None` means using all CPUs, which might cause hang if limited in systems like SLURM. Please set to a number allowed then.
```
My logs:
```log
[12:03] E Loading checkpoint shards: 100%|██████████| 14/14 [01:08<00:00,  4.91s/it]
[12:03] E [36m(RewardModelWorker pid=20854)[0m Some weights of Qwen3ForTokenClassification were not initialized from the model checkpoint at /data/rm/checkpoint/checkpoint-50 and are newly initialized: ['score.bias', 'score.weight']
[12:03] E [36m(RewardModelWorker pid=20854)[0m You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[12:03] O [36m(CriticWorker pid=20853)[0m Critic use_remove_padding=False[32m [repeated 3x across cluster][0m
[12:03] O [36m(RewardModelWorker pid=20854)[0m Skipping monkey patch for Qwen3ForTokenClassification as use_fused_kernels is False or fused_kernels_backend is None
[12:03] O [36m(RewardModelWorker pid=21248)[0m Skipping monkey patch for Qwen3ForTokenClassification as use_fused_kernels is False or fused_kernels_backend is None
[12:03] O [36m(RewardModelWorker pid=20854)[0m NCCL version 2.21.5+cuda12.4
[12:47] E [36m(ActorRolloutRefWorker pid=1506, ip=10.23.72.230)[0m Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in Qwen3ForCausalLM is torch.float32. You should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2", torch_dtype=torch.float16)`
[12:47] E [36m(ActorRolloutRefWorker pid=1506, ip=10.23.72.230)[0m You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[12:47] E [36m(RewardModelWorker pid=21248)[0m
[12:47] E Loading checkpoint shards:  93%|█████████▎| 13/14 [01:07<00:05,  5.36s/it]
```
